/**
 * Generates user-facing diagnostic reports from model prediction outputs.
 * Converts raw probabilities into structured, readable reports.
 */

import {
  CONDITIONS_CONFIG,
  LIKELIHOOD_THRESHOLDS,
} from '../config/conditionsConfig.js'

const DEFAULT_THRESHOLD = Number(process.env.REPORT_THRESHOLD) || 0.35
const RECOMMENDATION_SUFFIX =
  'Correlation with symptoms and clinical evaluation is recommended.'

/**
 * Get human-readable likelihood label from probability.
 */
function getLikelihood(probability, thresholds = LIKELIHOOD_THRESHOLDS) {
  if (probability >= thresholds.likely) return 'Likely'
  if (probability >= thresholds.possible) return 'Possible'
  return null
}

/**
 * Format condition label for display (e.g., Pleural_Thickening → Pleural Thickening).
 */
function formatLabel(label) {
  const config = CONDITIONS_CONFIG[label]
  return config?.displayName ?? label.replace(/_/g, ' ')
}

/**
 * Generate natural-language assessment summary from top findings.
 */
function generateAssessmentSummary(findings) {
  if (findings.length === 0) {
    return `No significant findings were detected above the screening threshold. ${RECOMMENDATION_SUFFIX}`
  }

  const primary = findings[0]
  const primaryName = formatLabel(primary.label)

  if (findings.length === 1) {
    return `The results suggest ${primaryName.toLowerCase()}. ${RECOMMENDATION_SUFFIX}`
  }

  const secondary = findings[1]
  const secondaryName = formatLabel(secondary.label).toLowerCase()
  return `The results suggest ${primaryName.toLowerCase()}, with additional signs that may indicate ${secondaryName}. ${RECOMMENDATION_SUFFIX}`
}

/**
 * Generate unique report ID for the report.
 */
function generateReportId() {
  const now = new Date()
  const dateStr = now.toISOString().slice(0, 10).replace(/-/g, '')
  const timeStr = now.toTimeString().slice(0, 8).replace(/:/g, '')
  return `CX-${dateStr}-${timeStr}`
}

/**
 * Generate structured diagnostic report from model predictions.
 *
 * @param {Object} predictions - Map of condition label → probability (0–1)
 * @param {Object} options - Optional overrides
 * @param {number} options.threshold - Minimum probability to include (default: REPORT_THRESHOLD or 0.35)
 * @returns {Object} Structured report ready for display
 */
export function generateReport(predictions, options = {}) {
  const threshold = options.threshold ?? DEFAULT_THRESHOLD

  // Filter and sort: only conditions above threshold, sorted by confidence
  const entries = Object.entries(predictions || {})
    .filter(([, prob]) => typeof prob === 'number' && prob >= threshold)
    .sort(([, a], [, b]) => b - a)

  const findings = entries.map(([label, probability]) => {
    const likelihood = getLikelihood(probability)
    const config = CONDITIONS_CONFIG[label]
    return {
      label,
      displayName: formatLabel(label),
      probability,
      confidencePct: Math.round(probability * 100),
      likelihood: likelihood ?? 'Possible',
      description: config?.description ?? 'Finding detected in lung tissue.',
    }
  })

  // Build potential symptoms (dedupe by condition)
  const potentialSymptoms = {}
  for (const { label } of findings) {
    const config = CONDITIONS_CONFIG[label]
    if (config?.symptoms?.length) {
      potentialSymptoms[formatLabel(label)] = config.symptoms
    }
  }

  const now = new Date()
  const assessmentSummary = generateAssessmentSummary(findings)

  return {
    title: 'Chest X-Ray Diagnostic Report',
    date: now.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    }),
    time: now.toLocaleTimeString('en-US', {
      hour: 'numeric',
      minute: '2-digit',
    }),
    reportId: generateReportId(),
    assessmentSummary,
    findings,
    potentialSymptoms,
    recommendations: [
      'Clinical evaluation is recommended to confirm these findings.',
      'Correlate with patient symptoms and medical history.',
    ],
    disclaimer:
      'This report is generated by an AI system for informational purposes only and does not constitute a medical diagnosis. It should not replace professional medical interpretation. Please consult a qualified healthcare provider for clinical decision-making.',
  }
}
